-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PLANES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLANES` (
  `ID-PLAN` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE-PLAN` VARCHAR(45) NULL,
  PRIMARY KEY (`ID-PLAN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGISTRO-USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REGISTRO-USUARIOS` (
  `CLAVE-USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDO` VARCHAR(45) NOT NULL,
  `CORREO` VARCHAR(45) NOT NULL,
  `CLAVE` VARCHAR(45) NOT NULL,
  `PLANES_ID-PLAN` INT NOT NULL,
  PRIMARY KEY (`CLAVE-USUARIO`),
  INDEX `fk_REGISTRO-USUARIOS_PLANES1_idx` (`PLANES_ID-PLAN` ASC) VISIBLE,
  CONSTRAINT `fk_REGISTRO-USUARIOS_PLANES1`
    FOREIGN KEY (`PLANES_ID-PLAN`)
    REFERENCES `mydb`.`PLANES` (`ID-PLAN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROYECTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECTOS` (
  `ID-PROYECTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE-PROYECTO` VARCHAR(45) NULL,
  `REGISTRO-USUARIOS_CLAVE-USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID-PROYECTO`),
  INDEX `fk_PROYECTOS_REGISTRO-USUARIOS1_idx` (`REGISTRO-USUARIOS_CLAVE-USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_PROYECTOS_REGISTRO-USUARIOS1`
    FOREIGN KEY (`REGISTRO-USUARIOS_CLAVE-USUARIO`)
    REFERENCES `mydb`.`REGISTRO-USUARIOS` (`CLAVE-USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CARPETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARPETAS` (
  `ID-CARPETA` INT NOT NULL,
  `NOMBRE-CARPETA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID-CARPETA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REDES-SOCIALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REDES-SOCIALES` (
  `ID-RED-SOCIAL` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE-RED-SOCIAL` VARCHAR(45) NULL,
  PRIMARY KEY (`ID-RED-SOCIAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS-REDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS-REDES` (
  `REGISTRO-USUARIOS_CLAVE-USUARIO` INT NOT NULL,
  `REDES-SOCIALES_ID-RED-SOCIAL` INT NOT NULL,
  INDEX `fk_USUARIOS-REDES_REGISTRO-USUARIOS1_idx` (`REGISTRO-USUARIOS_CLAVE-USUARIO` ASC) VISIBLE,
  INDEX `fk_USUARIOS-REDES_REDES-SOCIALES1_idx` (`REDES-SOCIALES_ID-RED-SOCIAL` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS-REDES_REGISTRO-USUARIOS1`
    FOREIGN KEY (`REGISTRO-USUARIOS_CLAVE-USUARIO`)
    REFERENCES `mydb`.`REGISTRO-USUARIOS` (`CLAVE-USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS-REDES_REDES-SOCIALES1`
    FOREIGN KEY (`REDES-SOCIALES_ID-RED-SOCIAL`)
    REFERENCES `mydb`.`REDES-SOCIALES` (`ID-RED-SOCIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROYECTOS-CARPETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECTOS-CARPETAS` (
  `PROYECTOS_ID-PROYECTO` INT NOT NULL,
  `CARPETAS_ID-CARPETA` INT NOT NULL,
  INDEX `fk_PROYECTOS-CARPETAS_PROYECTOS1_idx` (`PROYECTOS_ID-PROYECTO` ASC) VISIBLE,
  INDEX `fk_PROYECTOS-CARPETAS_CARPETAS1_idx` (`CARPETAS_ID-CARPETA` ASC) VISIBLE,
  CONSTRAINT `fk_PROYECTOS-CARPETAS_PROYECTOS1`
    FOREIGN KEY (`PROYECTOS_ID-PROYECTO`)
    REFERENCES `mydb`.`PROYECTOS` (`ID-PROYECTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROYECTOS-CARPETAS_CARPETAS1`
    FOREIGN KEY (`CARPETAS_ID-CARPETA`)
    REFERENCES `mydb`.`CARPETAS` (`ID-CARPETA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
